###**MiniProject 5 - Forest Fire**

Part II
Data
Files => "Employee.csv" "salary.csv" "not_active.csv"
Google Drive
The three files mentioned above is placed here:
https://drive.google.com/drive/u/0/folders/1uZTBgqKrf3xN5HKqHvJ4ZmyIm3TAykI0

**1. Find Maximum salary for each department only active employees and output requires `emp_id`.**



Expected result:

emp_id, department, max_salary
4,'sales',140
6,'marketing',150

In [ ]:
df = pd.read_csv("/content/employee.csv")
df = pd.read_csv("/content/employee.csv")
df.head()
list(df.columns)
df.head(10)

   emp_id  salary
0       1     100
1       2     120
2       3     145
3       4     140
4       5     100
5       6     150
6       7     250

In [ ]:
employee_df = pd.read_csv("/content/employee.csv")
df = pd.read_csv("/content/department.csv")
employee_df = pd.merge(employee_df, df, on='emp_id')
max_salary = employee_df.groupby('department')['salary'].max().reset_index()
merged_df = pd.merge(employee_df, max_salary, on='department')
merged_df = pd.merge(employee_df, max_salary, on='department')
filtered_df = merged_df[merged_df['salary_x'] == merged_df['salary_y']]
output_df = filtered_df[['emp_id', 'salary_x']]
print(tabulate(output_df, headers='keys', tablefmt='fancy_grid'))

╒════╤══════════╤════════════╕
│    │   emp_id │   salary_x │
╞════╪══════════╪════════════╡
│  2 │        3 │        145 │
├────┼──────────┼────────────┤
│  6 │        7 │        250 │
╘════╧══════════╧════════════╛

**2. All active/inactive employees (=emp_id) and their correspond department maximum salary.**

Expected result:

emp_id, department, max_salary
1,'sales',140
2,'sales',140
3,'sales',140
4,'sales',140
5,'marketing',150
6,'marketing',150
7,'marketing',150

In [ ]:
active_employee_df = pd.read_csv("/content/employee.csv")
df = pd.read_csv("/content/department.csv")
active_employee_df = pd.merge(active_employee_df, df, on='emp_id')
max_salary = active_employee_df.groupby('department')['salary'].max().reset_index()
merged_df = pd.merge(active_employee_df, max_salary, on='department')
print(tabulate(merged_df[['emp_id', 'department', 'salary_x', 'salary_y']], headers='keys', tablefmt='fancy_grid'))

╒════╤══════════╤══════════════╤════════════╤════════════╕
│    │   emp_id │ department   │   salary_x │   salary_y │
╞════╪══════════╪══════════════╪════════════╪════════════╡
│  0 │        1 │ sales        │        100 │        145 │
├────┼──────────┼──────────────┼────────────┼────────────┤
│  1 │        2 │ sales        │        120 │        145 │
├────┼──────────┼──────────────┼────────────┼────────────┤
│  2 │        3 │ sales        │        145 │        145 │
├────┼──────────┼──────────────┼────────────┼────────────┤
│  3 │        4 │ sales        │        140 │        145 │
├────┼──────────┼──────────────┼────────────┼────────────┤
│  4 │        5 │ marketing    │        100 │        250 │
├────┼──────────┼──────────────┼────────────┼────────────┤
│  5 │        6 │ marketing    │        150 │        250 │
├────┼──────────┼──────────────┼────────────┼────────────┤
│  6 │        7 │ marketing    │        250 │        250 │
╘════╧══════════╧══════════════╧════════════╧════════════╛