####**MINI PROJECT 12 - Parsing JSON and persist as a CSV file**

JSON files and its README are in git repo:
https://github.com/leninworld/parser_exercises
Complete all the exercises mentioned in the above repository.

In [ ]:
import json
import pandas as pd
from tabulate import tabulate

json_data = [
    {
        "name": "Raj",
        "age": 21,
        "marks": [
            {"english": 91},
            {"tamil": 99},
            {"math": 87},
            {"science": 89}
        ],
        "address": [
            {"20220101": "331 main road, chennai 600021"},
            {"20210101": "33 gandhi road, bangalore 600021"}
        ],
        "city": "chennai",
        "gender": "male",
        "salary": 200000
    },
    {
        "name": "Vim",
        "age": 28,
        "marks": [
            {"english": 93},
            {"tamil": 98},
            {"math": 99},
            {"science": 100}
        ],
        "address": [
            {"20190101": "11 MG road, chennai 600021"},
            {"20200101": "921 gandhi road, bangalore 600021"}
        ],
        "city": "bangalore",
        "gender": "female",
        "salary": 300000
    }
]

rows = []
for student in json_data:
    name = student["name"]
    age = student["age"]
    marks = {k: v for mark in student["marks"] for k, v in mark.items()}
    max_mark = max(marks.values())
    min_mark = min(marks.values())
    avg_mark = sum(marks.values()) / len(marks)
    recent_address = list(student["address"][-1].values())[0]
    city = student["city"]
    gender = student["gender"]
    salary = student["salary"]

    rows.append({
        "name": name,
        "age": age,
        "english": marks.get("english", None),
        "tamil": marks.get("tamil", None),
        "math": marks.get("math", None),
        "science": marks.get("science", None),
        "max_mark": max_mark,
        "min_mark": min_mark,
        "avg_mark": avg_mark,
        "recent_address": recent_address,
        "city": city,
        "gender": gender,
        "salary": salary
    })

df = pd.DataFrame(rows)
display(pd.DataFrame(df))

df.to_csv("student.csv", index=False)

print(tabulate(df, headers="keys", tablefmt="grid"))

,name,age,english,tamil,math,science,max_mark,min_mark,avg_mark,recent_address,city,gender,salary
0,Raj,21,91,99,87,89,99,87,91.5,"33 gandhi road, bangalore 600021",chennai,male,200000
1,Vim,28,93,98,99,100,100,93,97.5,"921 gandhi road, bangalore 600021",bangalore,female,300000

+----+--------+-------+-----------+---------+--------+-----------+------------+------------+------------+-----------------------------------+-----------+----------+----------+
|    | name   |   age |   english |   tamil |   math |   science |   max_mark |   min_mark |   avg_mark | recent_address                    | city      | gender   |   salary |
+====+========+=======+===========+=========+========+===========+============+============+============+===================================+===========+==========+==========+
|  0 | Raj    |    21 |        91 |      99 |     87 |        89 |         99 |         87 |       91.5 | 33 gandhi road, bangalore 600021  | chennai   | male     |   200000 |
+----+--------+-------+-----------+---------+--------+-----------+------------+------------+------------+-----------------------------------+-----------+----------+----------+
|  1 | Vim    |    28 |        93 |      98 |     99 |       100 |        100 |         93 |       97.5 | 921 gandhi road, bangalore 600021 | bangalore | female   |   300000 |
+----+--------+-------+-----------+---------+--------+-----------+------------+------------+------------+-----------------------------------+-----------+----------+----------+

In [ ]:
import json
import pandas as pd
from tabulate import tabulate

# Sample JSON data
twitter_data = [
    {
        "created_at": "Thu Jun 22 21:00:00 +0000 2017",
        "id": 877994604561387500,
        "id_str": "877994604561387520",
        "text": "Creating a Grocery List Manager Using Angular, Part 1: Add &amp; Display Items https://t.co/xFox78juL1 #Angular",
        "truncated": False,  # Corrected 'false' to 'False'
        "entities": {
            "hashtags": [
                {
                    "text": "Angular",
                    "indices": [103, 111]
                }
            ],
            "symbols": [],
            "user_mentions": [],
            "urls": [
                {
                    "url": "https://t.co/xFox78juL1",
                    "expanded_url": "http://buff.ly/2sr60pf",
                    "display_url": "buff.ly/2sr60pf",
                    "indices": [79, 102]
                }
            ]
        },
        "source": "<a href=\"http://bufferapp.com\" rel=\"nofollow\">Buffer</a>",
        "user": {
            "id": 772682964,
            "id_str": "772682964",
            "name": "SitePoint JavaScript",
            "screen_name": "SitePointJS",
            "location": "Melbourne, Australia",
            "description": "Keep up with JavaScript tutorials, tips, tricks and articles at SitePoint.",
            "url": "http://t.co/cCH13gqeUK",
            "entities": {
                "url": {
                    "urls": [
                        {
                            "url": "http://t.co/cCH13gqeUK",
                            "expanded_url": "https://www.sitepoint.com/javascript",
                            "display_url": "sitepoint.com/javascript",
                            "indices": [0, 22]
                        }
                    ]
                },
                "description": {
                    "urls": []
                }
            },
            "protected": False,  # Corrected 'false' to 'False'
            "followers_count": 2145,
            "friends_count": 18,
            "listed_count": 328,
            "created_at": "Wed Aug 22 02:06:33 +0000 2012",
            "favourites_count": 57,
            "utc_offset": 43200,
            "time_zone": "Wellington"
        }
    }
]

# Parse and transform JSON to DataFrame
rows = []
for tweet in twitter_data:
    user = tweet["user"]
    rows.append({
        "id": tweet["id"],
        "created_at": tweet["created_at"],
        "source": tweet["source"].split(">")[-2].split("<")[0],
        "screen_name": user["screen_name"],
        "location": user["location"],
        "description": user["description"],
        "url": user["url"],
        "followers_count": user["followers_count"],
        "friends_count": user["friends_count"],
        "listed_count": user["listed_count"],
        "favourites_count": user["favourites_count"]
    })

# Create DataFrame
df = pd.DataFrame(rows)
display(pd.DataFrame(df))
# Save DataFrame to CSV
df.to_csv("twitter.csv", index=False)

# Display the DataFrame in grid format
print(tabulate(df, headers="keys", tablefmt="grid"))

,id,created_at,source,screen_name,location,description,url,followers_count,friends_count,listed_count,favourites_count
0,877994604561387500,Thu Jun 22 21:00:00 +0000 2017,Buffer,SitePointJS,"Melbourne, Australia","Keep up with JavaScript tutorials, tips, trick...",http://t.co/cCH13gqeUK,2145,18,328,57

+----+--------------------+--------------------------------+----------+---------------+----------------------+----------------------------------------------------------------------------+------------------------+-------------------+-----------------+----------------+--------------------+
|    |                 id | created_at                     | source   | screen_name   | location             | description                                                                | url                    |   followers_count |   friends_count |   listed_count |   favourites_count |
+====+====================+================================+==========+===============+======================+============================================================================+========================+===================+=================+================+====================+
|  0 | 877994604561387500 | Thu Jun 22 21:00:00 +0000 2017 | Buffer   | SitePointJS   | Melbourne, Australia | Keep up with JavaScript tutorials, tips, tricks and articles at SitePoint. | http://t.co/cCH13gqeUK |              2145 |              18 |            328 |                 57 |
+----+--------------------+--------------------------------+----------+---------------+----------------------+----------------------------------------------------------------------------+------------------------+-------------------+-----------------+----------------+--------------------+